### PR TITLE
[FEATURE] Customizable wait time

### PR DESCRIPTION
**Pull request by GuilhermeRameh**
Solves: #638 

CHANGES:
I added an input() in main.py that prompts the user to input his custom time, with try and except if the input is not an int.
Then it passes it as an argument to start_apply, and start_applying.

TESTS:
All previous tests have passed.

### CODE REVIEW

**Comment by GuilhermeRameh** [comment]
This is my first contribution to a project like this, so if anything needs to be changed i would be happy to do so! Thanks in advance.

**Comment by feder-cr** [comment]
@GuilhermeRameh resolve the conflicts, thanks

**Comment by GuilhermeRameh** [comment]
I believe the conflicts are resolved now!

**Comment by sarob** [comment]
Hi @GuilhermeRameh. Myself I would prefer not slow down running the app and instead add the the value to app_config.py. 

@cjbbb thoughts?

**Comment by GuilhermeRameh** [comment]
You mean change the value directly in the app_config.py? Yeah, it makes sense. I wasnt sure what was better, a prompt to the user or changing the variable directly. Thanks for the input

**Pull request closed without merging**
