### PR TITLE
Fixed the linkedin update

### PR DESCRIPTION
**Pull request by RushiChaganti**
Fixed this error 
Form submission failed with errors: [<selenium.webdriver.remote.webelement.WebElement

### CODE REVIEW

**Comment by MrTpat** [comment]
I think the PR I opened here: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/458

better addresses the problem of LinkedIn updates. It allows us to keep multiple parsers. Because everyone seems to have different LinkedIn page elements loading, it allows us to try many different methods of parsing.

**Comment by RushiChaganti** [comment]
@MrTpat  can you contact me on telegram

**Comment by feder-cr** [comment]
@RushiChaganti @MrTpat any update?

**Comment by RushiChaganti** [comment]
I've noticed that many users on GitHub have reported issues related to this behavior they've encountered with LinkedIn. So, I propose creating an automated system that retrieves class names whenever LinkedIn makes changes and updates the code accordingly.
@feder-cr @MrTpat

**Comment by MrTpat** [comment]
@RushiChaganti good idea! but i feel as though this solution would have one problem: its not guaranteed that each linkedin user will be interacting with the same linkedin front end, meaning different users can have different class names.

**Comment by RushiChaganti** [comment]
Yeah i agree on that @MrTpat  do you have telegram by any chance lets discuss it over there

**Comment by MrTpat** [comment]
https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/458

@RushiChaganti i fixed this PR. i believe it is a good solution that is flexible and doesnt tie us down to a single strategy.

**Pull request closed without merging**
