### PR TITLE
Added Zipcode to Addresses in Auto Jobs Applier (#407)  Issue Resolved: #407

### PR DESCRIPTION
**Pull request by RushiChaganti**
This PR addresses the issue of missing zip codes in addresses by implementing the following changes:

-     Added a field to include zip codes in the address format where applicable.
-     Updated any address-related functions and data structures to support zip code inclusion.
-     Refactored existing code to ensure compatibility with the new zip code field.

These changes should ensure that the bot now fully supports addresses with zip codes

### CODE REVIEW

**Review by air55555 — APPROVED** [review]

**Comment by feder-cr** [comment]
@RushiChaganti please update also the readme

**Comment by RushiChaganti** [comment]
@feder-cr Apologies for the delay, I hadn't checked GitHub as I was focused on another part of the project.

**Comment by feder-cr** [comment]
@RushiChaganti @air55555 I really don't understand how this modification can work if lib_resume_builder_AIHawk is not updated.

**Comment by RushiChaganti** [comment]
I've created a new program that generates CVs using the plain_text_resume, but it included the zip code field. I think I need to update the lib_resume_builder_AIHawk to add this functionality, so I'll go ahead and update the library."

**Comment by RushiChaganti** [comment]
Hey @feder-cr,
I’ve made a pull request in the lib_resume_AIHawk repo. Please check it out!

**Pull request merged**
