### PR TITLE
changes - making Hawk to evaluate before applying to job 

### PR DESCRIPTION
**Pull request by surapuramakhil**
https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/538

code in Action
```sh
2024-10-16 20:55:29.662 | DEBUG    | src.llm.llm_manager:log_request:237 - Log entry written to file: data_folder/output/open_ai_calls.json
2024-10-16 20:55:29.662 | DEBUG    | src.llm.llm_manager:__call__:263 - Request successfully logged
2024-10-16 20:55:29.664 | DEBUG    | src.llm.llm_manager:is_job_suitable:628 - Job suitability output: Score: 9  
Reasoning: The candidate meets most of the hard requirements outlined in the job description. They have over 3 years of experience in software development, specifically with Java and AWS, which are the most important technical skills. The candidate has experience in product design and development, as well as hosting services in AWS cloud technologies. They have demonstrated the ability to manage competing priorities in a fast-paced environment through their roles and responsibilities. The only slight gap is that while they have strong communication skills, the resume does not explicitly highlight experience in negotiation, which is a soft requirement. Overall, the candidate is highly suitable for the position.
2024-10-16 20:55:29.664 | INFO     | src.llm.llm_manager:is_job_suitable:631 - Job suitability score: 9
2024-10-16 20:55:29.664 | DEBUG    | src.aihawk_easy_applier:job_apply:134 - Attempting to click 'Easy Apply' button
2024-10-16 20:55:29.977 | DEBUG    | src.aihawk_easy_applier:job_apply:137 - 'Easy Apply' button clicked successfully
2024-10-16 20:55:29.978 | DEBUG    | src.aihawk_easy_applier:job_apply:139 - Filling out application form

```

### CODE REVIEW

**Comment by surapuramakhil** [comment]
@feder-cr request to review this MR.

**Comment by feder-cr** [comment]
Ok

**Comment by surapuramakhil** [comment]
@sarob resolved conflicts.

I ran new prompt design - its working great only applying for suitable role, its rejecting if my profile is not a match (like not even a chance). I have done manual testing something like that.

**Comment by sarob** [comment]
merge #598 for additional logging to support your feature

**Comment by surapuramakhil** [comment]
@sarob just checked your MR https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/598 added few review comments.

**Comment by feder-cr** [comment]
very good work @surapuramakhil please write em on telegram

**Pull request merged**
