### PR TITLE
Update job information parsing to match current webpage structure

### PR DESCRIPTION
**Pull request by moudimash99**
Hi there,

I noticed that the job information wasn't being parsed correctly in the function **extract_job_information_from_tile** due to some changes in the webpage structure. I updated the parsing code to align with the new HTML layout.

Changes:

- Updated selectors for job title, link, company, and location.
- Changed **apply_method** finder, as now there's no distinct identifier for apply_method vs other footer divs
I'm new to contributing, so I'm not sure if this is the right ettiquete . I’d appreciate any feedback or suggestions to improve this!

Thanks for your time!

Best,
Mohammad Machaka

### CODE REVIEW

**Comment by moudimash99** [comment]
@feder-cr is it working currently for you guys? In fact I'm not sure if this problem is global or different based on environments. Bernadette for me previously it wasn't working

**Comment by feder-cr** [comment]
@moudimash99 for me bot work correctly, please create a PR for each case

**Comment by moudimash99** [comment]
It's only 1 function that is changed. Intresting, so for you , the HTML parsing works? it's not skipping applying? is it possible we're having different HTML pages? see [here ](https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/418) where somebody else's problem was solved with this
image

**Comment by feder-cr** [comment]
@moudimash99 We need a version that fits as many people as possible

**Comment by moudimash99** [comment]
@feder-cr what I don't understand is how we have different html identifiers. Do you have a clue why? It seems this is a widespread issue

**Comment by moudimash99** [comment]
@feder-cr what I don't understand is how we have different html identifiers. Do you have a clue why? It seems this is a widespread issue

**Comment by feder-cr** [comment]
@moudimash99 no idea

**Pull request closed without merging**
