### PR TITLE
Extraction chains

### PR DESCRIPTION
**Pull request by MrTpat**
So this introduces a concept of "extraction chains" for our job parsing.  Certain issues: (https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/114) are happening because there are parsing changes necessary when LinkedIn changes something on their end. Instead of changing our parsing code each time, we can add a new parser here when we encounter some new linkedin HTML format.

Shoutout to @pafthinder for his initial correct implementation which I've included here. This fixes THAT issue and fixes issues I had been having myself.

### CODE REVIEW

**Comment by feder-cr** [comment]
@MrTpat i will create v4 for this, ok?

**Comment by feder-cr** [comment]
@MrTpat  please do on PR on V4 https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/tree/v4

**Comment by feder-cr** [comment]
@MrTpat any updates?

**Comment by AdrianoLusso** [comment]
Hi @feder-cr . I try this v4 version merged with the main because i has the same issue from #114. But the problem isn't yet solved. When i run the command in the console, nothing happens. Here it is an img:
image

**Pull request closed without merging**
