### PR TITLE
Added support for models through OpenRouter

### PR DESCRIPTION
**Pull request by gauravdhiman**
Added support for models through OpenRouter (https://openrouter.ai/)

### CODE REVIEW

**Comment by feder-cr** [comment]
@gauravdhiman update readme

**Comment by gauravdhiman** [comment]
@feder-cr did it get merged or refused ?

**Comment by coxde** [comment]
> @feder-cr did it get merged or refused ?

I think it got refused because lack of readme doc, I can re-open a new pr if you don't mind

**Comment by gauravdhiman** [comment]
oh ok, can you pls reopen it. I will update the README
or shall I create an new one ?

**Comment by coxde** [comment]
You can open a new one (cuz I'm not a contributor). You might also want to check their latest note for developers: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/commit/96c009a86ee2d191f6954f181a6b5829eb99fa4c

**Comment by coxde** [comment]
> oh ok, can you pls reopen it. I will update the README or shall I create an new one ?

You can open a new one (cuz I'm not a contributor). You might also want to check their latest note for developers: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/commit/96c009a86ee2d191f6954f181a6b5829eb99fa4c

**Pull request closed without merging**
